// Code generated by "stringer -type level -output level_string.go"; DO NOT EDIT.

package level

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Trace - -2]
	_ = x[Debug - -1]
	_ = x[Info-0]
	_ = x[Warn-1]
	_ = x[Error-2]
	_ = x[Fatal-3]
}

const _Level_name = "TraceDebugInfoWarnErrorFatal"

var _Level_index = [...]uint8{0, 5, 10, 14, 18, 23, 28}

func (i Level) String() string {
	i -= -2
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "level(" + strconv.FormatInt(int64(i+-2), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
