version: "2"

#output:
#  show-stats: true
#  sort-order:
#    - file
#    - linter

linters:
  enable:
    - misspell
    - govet
    - errcheck
    - goconst
    - unparam
    - ineffassign
    - nakedret
    - gocyclo
    - goimports
    - lll
    - dupl

linters-settings:
  dupl:
    threshold: 400
  lll:
    line-length: 170

issues:
  exclude-rules:
    - text: "Error return value of .* is not checked"
      linters:
        - errcheck
  exclude-dirs:
    - vendor
    - proto
    - test
  exclude-files:
    - ".*_test\\.go$"
    - ".*_string\\.go$"
    - "pkg/response/actions/k8s/control.go"
    - "pkg/response/actions/k8s/search.go"
