// Code generated by "stringer -type ErrCode -output error_code_string.go"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUCCESS-0]
	_ = x[StoreSvcBaseErrorCode-10000]
	_ = x[StoreSvcOperateAdapterFailed-10000]
}

const (
	_ErrorCode_name_0 = "SUCCESS"
	_ErrorCode_name_1 = "StoreSvcBaseErrorCode"
)

func (i ErrCode) String() string {
	switch {
	case i == 0:
		return _ErrorCode_name_0
	case i == 10000:
		return _ErrorCode_name_1
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
