server:
  addr: :9094
#health:
#  addr: :3001
#metrics:
#  addr: :4001
logger:
  # 日志类型 default: go-admin-core构建的默认日志插件, zap: zap插件
  type: default
  # 日志存放路径，关闭控制台日志后，日志文件存放位置
  path: temp/logs
  # 日志输出，file：文件，default：命令行，其他：命令行
  stdout: default #控制台日志，启用后，不输出到文件
  # 日志等级, trace, debug, info, warn, error, fatal
  level: trace
  # 日志格式 json json格式
  formatter: default
database:
  url: ''
  name: tenant
  timeout: 10
oauth2:
  id: '222222'
  secret: '22222222'
  redirectURL: http://localhost:9094/tenant
  scopes:
    - tenant
  endpoint:
    authURL: http://localhost:9096/oauth2/oauth/authorize
    tokenURL: http://localhost:9096/oauth2/oauth/token
